### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by daniel5984** [7eu7d7/DreamArtist-sd-webui-extension#11]
Weights from pretrained model not used in ConvNeXt: ['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'callbacks', 'lr_schedulers']
use convnext discriminator
  0%|                                                | 0/100000 [00:00<?, ?it/s]
Applying xformers cross attention optimization.
Error completing request
Arguments: ('dreamArtist', '0.003', 1, '/notebooks/testing_Dreamartist', 'textual_inversion', 512, 512, 100000, 500, 500, '/notebooks/stable-diffusion-webui/textual_inversion_templates/style.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512, 5.0, '/storage/models/v1-5-pruned-emaonly.ckpt', True, True, 1, 1) {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/notebooks/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/cptuning.py", line 413, in train_embedding
    output = shared.sd_model(x, c_in, scale=cfg_scale)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/notebooks/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 879, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/notebooks/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/cptuning.py", line 269, in p_losses_hook
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by mykeehu** [comment]
[This might be the solution](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4271) to the bug, but Automatic has not yet allowed it.
