### ISSUE TITLE
Can't get tab to show in GUI

### ISSUE THREAD

**Issue by west1778** [7eu7d7/DreamArtist-sd-webui-extension#12]
I followed the instructions and git clone https://github.com/7eu7d7/DreamArtist-sd-webui-extension.git extensions/DreamArtist load it up and nothing. Also, get an error when I try and update Webui extensions but I'm assuming that's because it's not in the WebUI list of extensions. Any help would be welcomed though thank you.

File "C:\AiArt\NewSD\stable-diffusion-webui\modules\ui_extensions.py", line 59, in check_updates
    ext.check_updates()
  File "C:\AiArt\NewSD\stable-diffusion-webui\modules\extensions.py", line 59, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "C:\AiArt\NewSD\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "C:\AiArt\NewSD\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 763, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AiArt\\NewSD\\stable-diffusion-webui\\extensions\\DreamArtist\\.git\\FETCH_HEAD'

Error checking updates for stable-diffusion-webui-prompt-utilities:
Traceback (most recent call last):
  File "C:\AiArt\NewSD\stable-diffusion-webui\modules\ui_extensions.py", line 59, in check_updates
    ext.check_updates()
  File "C:\AiArt\NewSD\stable-diffusion-webui\modules\extensions.py", line 59, in check_updates
    for fetch in repo.remote().fetch("--dry-run"):
  File "C:\AiArt\NewSD\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 886, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress,
  File "C:\AiArt\NewSD\stable-diffusion-webui\venv\lib\site-packages\git\remote.py", line 763, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AiArt\\NewSD\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-prompt-utilities\\.git\\FETCH_HEAD'

**Comment by dikasterion** [comment]
![이미지 006](https://user-images.githubusercontent.com/117759030/201689500-280457cc-49db-4c6c-9f15-6d0a11940e18.png)
did you check "train" tab?

**Comment by west1778** [comment]
> ![이미지 006](https://user-images.githubusercontent.com/117759030/201689500-280457cc-49db-4c6c-9f15-6d0a11940e18.png) did you check "train" tab?

OMG, I'm an idiot thank you so much! Was looking for an actual tab of its own. lol Thanks, it is there. <3
