### ISSUE TITLE
Input and model on different devices error when training with reconstruction

### ISSUE THREAD

**Issue by zhupeter010903** [7eu7d7/DreamArtist-sd-webui-extension#13]
I got the following error on google colab when trying to train with reconstruction turned on. 

```Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/dream_artist/ui.py", line 36, in train_embedding
    embedding, filename = modules.dream_artist.cptuning.train_embedding(*args)
  File "/content/stable-diffusion-webui/modules/dream_artist/cptuning.py", line 413, in train_embedding
    x_samples_ddim = shared.sd_model.decode_first_stage.__wrapped__(shared.sd_model, output[2])  # forward with grad
  File "/content/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 763, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/autoencoder.py", line 331, in decode
    z = self.post_quant_conv(z)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
```

I also got 
```
Traceback (most recent call last):
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/cptuning.py", line 486, in train_embedding
    processed = processing.process_images(p)
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/modules/processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/modules/processing.py", line 442, in process_images_inner
    file.write(processed.infotext(p, 0))
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/modules/processing.py", line 281, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
  File "/content/gdrive/.shortcut-targets-by-id/1VNhtnoJC8AkKUr4-kCbT3hxMSzfiOGCd/sd/stable-diffusion-webui/modules/processing.py", line 411, in create_infotext
    negative_prompt_text = "\nNegative prompt: " + p.negative_prompt if p.negative_prompt else ""
TypeError: can only concatenate str (not "tuple") to str
```

When trying to read from txt2img for making previews. But I managed to bypass the problem by replacing line 470 
```
p.negative_prompt = preview_prompt.replace(ds.placeholder_token, ds.placeholder_token + '-neg') if use_negative else preview_negative_prompt,
```
 of cptuning.py with 
```
p.negative_prompt = preview_negative_prompt
```
which makes more sense to me.

**Comment by 7eu7d7** [comment]
These fixed in new version.
