### ISSUE TITLE
AttributeError: module 'modules.script_callbacks' has no attribute 'on_ui_train_tabs'

### ISSUE THREAD

**Issue by TiagoTiago** [7eu7d7/DreamArtist-sd-webui-extension#16]
I get the following when launching the webui:

```
Error loading script: dream_artist_main.py
Traceback (most recent call last):
  File "/home/username/Stab-Diff/AUTOMATIC1111/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/home/username/Stab-Diff/AUTOMATIC1111/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist_main.py", line 156, in <module>
    script_callbacks.on_ui_train_tabs(on_ui_train_tabs)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_ui_train_tabs'

```

And there seems to be no DreamArtist tab.

**Comment by 7eu7d7** [comment]
The new version fix it.

**Comment by TiagoTiago** [comment]
How do I check which version I got?

**Comment by TiagoTiago** [comment]
Ah, I had to update the webui itself it seems, ok.
