### ISSUE TITLE
hyper_params.json not found for embedding training

### ISSUE THREAD

**Issue by tkclimb** [7eu7d7/DreamArtist-sd-webui-extension#21]
I cannot run train embedding after created it because of missing `hyper_param.json`.
How do I create it? or I have to prepare it before training?

```
Error completing request
Arguments: ('my_keyword', '0.005', 1, '/workspace/my_keyword', 'textual_inversion', 576, 1024, 100, 0, 0, '/workspace/my_keyword/prompt-template.txt', True, True, '', '', 20, 0, 7, -1.0, 512, 512, 10.0, '', True, True, 1, 1) {}
Traceback (most recent call last):
  File "/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/cptuning.py", line 367, in train_embedding
    with open(os.path.join(log_directory, 'hyper_param.json'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'textual_inversion/2022-11-16/my_keyword/hyper_param.json'
```

**Comment by tkclimb** [comment]
Now I found just making the directory under your webui process is running works e.g. `mkdir -p textual_inversion/2022-11-17/my_keyword` in above case.
