### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 231 but got size 154 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by PascalTemel** [7eu7d7/DreamArtist-sd-webui-extension#4]
![image](https://user-images.githubusercontent.com/13536271/201500008-882564fe-5d39-43ed-90c4-024d279127f3.png)

Tried training a nahida embedding with 5 pictures, these are my settings:

![image](https://user-images.githubusercontent.com/13536271/201500031-32060fe7-bbd6-4a1c-b6b2-b7a3c23d14b8.png)

**Comment by PascalTemel** [comment]
Seems like this is an issue with the prompt template file, using only that has only `[filewords]` works (though I get another error)

**Comment by 7eu7d7** [comment]
Is there a full report of errors? It may be better to train without using the [filewords] version.

**Comment by PascalTemel** [comment]
> Is there a full report of errors? It may be better to train without using the [filewords] version.

Thanks for the reply, what template would you recommend for training?

**Comment by IdiotSandwichTheThird** [comment]
Any template that does not change should work. I'm using just a .txt file with 1 word.

**Comment by tsukimiya** [comment]
Perhaps, but I had the same problem.

I encountered this problem when I ran it again with the same conditions using different data after one successful run with the same conditions.
```
Training at rate of 0.005 until step 2000
Preparing dataset...
100%|█████████████████████████████████████████████| 5/5 [00:01<00:00,  3.14it/s]
[Epoch 4: 0/2]loss: 0.0608956, grad:0.0001024, grad_neg:0.0000176:   0%| | 9/200
Applying xformers cross attention optimization.
Error completing request
Arguments: ('test', '0.005', 1, '/notebooks/train_data/test', 'dream_artist', 512, 512, 2000, 500, 500, '/notebooks/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', True, False, '', '', 20, 0, 7, -1.0, 512, 512, 5.0, '', True, False, 1, 1) {}
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/notebooks/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/notebooks/stable-diffusion-webui/modules/dream_artist/ui.py", line 36, in train_embedding
    embedding, filename = modules.dream_artist.cptuning.train_embedding(*args)
  File "/notebooks/stable-diffusion-webui/modules/dream_artist/cptuning.py", line 405, in train_embedding
    c_in = torch.cat([uc, c])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 154 but got size 77 for tensor number 1 in the list.
```

**Comment by neonr-0** [comment]
Have similar issue, can run 2-3 iterations then stop with with this error. (training on CPUs 2x Xeon Silver 4114, but mostly load on 1 CPU)

```
Training at rate of 0.005 until step 7000
Preparing dataset...
100%|██████████| 128/128 [06:39<00:00,  3.12s/it]
  0%|          | 0/99977 [00:00<?, ?it/s]
Error completing request
Arguments: ('Chii-A3', '0.005:7000, 1e-3:22000, 1e-5', 1, '/workspace/stable-diffusion-webui/dataset', 'textual_inversion', 768, 768, 100000, 500, 500, '/workspace/stable-diffusion-webui/textual_inversion_templates/tags.txt', True, False, '(masterpiece), (best quality), ultra hyper detailed,highres, portrait,portfolio 1girl, Chii-A3, red dress', 'lowres, bad anatomy, bad hands, text, error,  missing fingers, extra digit, fewer digits, cropped, worst quality, low  quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, Chii-A3-neg', 20, 4, 8.5, 2144721791.0, 512, 512, 3.0, '/workspace/stable-diffusion-webui/models/convnext/checkpoint-best_t5.pth', True, True, 1, 1) {}
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/workspace/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/workspace/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension-master/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/workspace/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension-master/scripts/dream_artist/cptuning.py", line 408, in train_embedding
    c_in = torch.cat([uc, c])
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 77 but got size 154 for tensor number 1 in the list.
```

also randomly getting this error:

```
Training at rate of 0.005 until step 7000
Preparing dataset...
100%|██████████| 128/128 [06:37<00:00,  3.11s/it]
use convnext discriminator
  0%|          | 0/99986 [02:19<?, ?it/s]
Error completing request
Arguments: ('Chii-A3', '0.005:7000, 1e-3:22000, 1e-5', 1, '/workspace/stable-diffusion-webui/dataset', 'textual_inversion', 768, 768, 100000, 500, 500, '/workspace/stable-diffusion-webui/textual_inversion_templates/tags.txt', True, True, '(masterpiece), (best quality), ultra hyper detailed,highres, portrait,portfolio 1girl, red dress, Chii-A3', 'lowres, bad anatomy, bad hands, text, error,  missing fingers, extra digit, fewer digits, cropped, worst quality, low  quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, Chii-A3-neg', 20, 4, 8.5, 2144721791.0, 512, 512, 3.0, '/workspace/stable-diffusion-webui/models/convnext/checkpoint-best_t5.pth', True, True, 1, 1) {}
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/workspace/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/workspace/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension-master/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/workspace/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension-master/scripts/dream_artist/cptuning.py", line 439, in train_embedding
    f"grad:{embedding.vec.grad.detach().cpu().abs().mean().item():.7f}, "
AttributeError: 'NoneType' object has no attribute 'detach'
```

**Comment by kou201** [comment]
![image](https://user-images.githubusercontent.com/55701610/201718365-ba042da6-28c5-4ec6-8f83-8a5362c4d707.png)

same problem here

**Comment by 7eu7d7** [comment]
Expanding the prompt length will lead to inconsistent positive and negative prompt lengths and needs to turn off expansion.

![image](https://user-images.githubusercontent.com/31194890/202395669-2e1ec4f7-3a01-4166-aaa0-c1baf4965d1e.png)
