### ISSUE TITLE
Seems to need --disable-safe-unpickle on embeds DA created?

### ISSUE THREAD

**Issue by TumnusB** [7eu7d7/DreamArtist-sd-webui-extension#46]
Its detecting the embeds as bad, dunno why?

`venv "E:\DreamArtist-stable-diffusion\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Launching Web UI with arguments: --xformers
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [925997e9] from E:\DreamArtist-stable-diffusion\models\Stable-diffusion\animefull-final-pruned.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 0 words embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Error verifying pickled file from E:\DreamArtist-stable-diffusion\embeddings\Elins-neg.pt:
Traceback (most recent call last):
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 84, in check_pt
    check_zip_filenames(filename, z.namelist())
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 76, in check_zip_filenames
    raise Exception(f"bad file inside {filename}: {name}")
Exception: bad file inside E:\DreamArtist-stable-diffusion\embeddings\Elins-neg.pt: Elins-neg/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Error loading emedding Elins-neg.pt:
Traceback (most recent call last):
  File "E:\DreamArtist-stable-diffusion\modules\dream_artist\cptuning.py", line 137, in load_words_embeddings
    process_file(fullfn, fn)
  File "E:\DreamArtist-stable-diffusion\modules\dream_artist\cptuning.py", line 107, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Error verifying pickled file from E:\DreamArtist-stable-diffusion\embeddings\Elins.pt:
Traceback (most recent call last):
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 84, in check_pt
    check_zip_filenames(filename, z.namelist())
  File "E:\DreamArtist-stable-diffusion\modules\safe.py", line 76, in check_zip_filenames
    raise Exception(f"bad file inside {filename}: {name}")
Exception: bad file inside E:\DreamArtist-stable-diffusion\embeddings\Elins.pt: Elins/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

Error loading emedding Elins.pt:
Traceback (most recent call last):
  File "E:\DreamArtist-stable-diffusion\modules\dream_artist\cptuning.py", line 137, in load_words_embeddings
    process_file(fullfn, fn)
  File "E:\DreamArtist-stable-diffusion\modules\dream_artist\cptuning.py", line 107, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Loaded a total of 0 words embeddings.
Embeddings:`

**Comment by TumnusB** [comment]
this is on standalone not extension
