### ISSUE TITLE
can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [7eu7d7/DreamArtist-sd-webui-extension#49]
Not too sure what's going on.
`Error completing request
Arguments: (...)

Traceback (most recent call last):
  File "C:\Git\SD15\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Git\SD15\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Git\SD15\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "C:\Git\SD15\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 626, in train_embedding
    processed = processing.process_images(p)
  File "C:\Git\SD15\modules\processing.py", line 470, in process_images
    res = process_images_inner(p)
  File "C:\Git\SD15\modules\processing.py", line 575, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Git\SD15\modules\processing.py", line 707, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Git\SD15\modules\sd_samplers.py", line 527, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Git\SD15\modules\sd_samplers.py", line 439, in launch_sampling
    return func()
  File "C:\Git\SD15\modules\sd_samplers.py", line 527, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Git\SD15\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Git\SD15\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Git\SD15\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Git\SD15\modules\sd_samplers.py", line 354, in forward
    denoised = self.combine_denoised(x_out, conds_list, uncond, cond_scale)
  File "C:\Git\SD15\modules\sd_samplers.py", line 309, in combine_denoised
    denoised[i] += (x_out[cond_index] - denoised_uncond[i]) * (weight * cond_scale)
TypeError: can't multiply sequence by non-int of type 'float'`

I have followed instructions and made a positive prompt and a negative prompt including the embeddings in the txt2img tab.
Files are captioned.

**Comment by ARandomUserFromGithub** [comment]
I changed accumulation step to 2, and reduced the complexity of the prompts a bit, and now it seems to work.
I'm not too sure what happened, but tinkering around with it did the trick.

**Comment by Heathen** [comment]
Same issue here.

**Comment by ARandomUserFromGithub** [comment]
I just faced the same issue again and I realize that whatever I did to make it work the last time, now it don't work anymore and the "accumulation step" slider seemingly isn't what resolved the issue the last time... So clueless
