### ISSUE TITLE
Crash during image generation when checking Read parameters from txt2img tab 

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [7eu7d7/DreamArtist-sd-webui-extension#5]
When checking the `Read parameters (prompt, etc...) from txt2img tab when making previews` box it will crash during image generation.
Full Crash:
```
Error completing request
Arguments: ('testv2', '0.005', 1, '/home/bunny/stable-diffusion-webui/dataset/', 'textual_inversion', 512, 512, 100000, 5, 500, '/home/bunny/stable-diffusion-webui/textual_inversion_templates/none.txt', True, True, '', '', 27, 0, 7, 1337.0, 512, 512, 5.0, '', True, True, 1, 1) {}
Traceback (most recent call last):
  File "/home/bunny/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/bunny/stable-diffusion-webui/webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "/home/bunny/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/ui.py", line 30, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/home/bunny/stable-diffusion-webui/extensions/DreamArtist/scripts/dream_artist/cptuning.py", line 489, in train_embedding
    processed = processing.process_images(p)
  File "/home/bunny/stable-diffusion-webui/modules/processing.py", line 423, in process_images
    res = process_images_inner(p)
  File "/home/bunny/stable-diffusion-webui/modules/processing.py", line 442, in process_images_inner
    file.write(processed.infotext(p, 0))
  File "/home/bunny/stable-diffusion-webui/modules/processing.py", line 281, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
  File "/home/bunny/stable-diffusion-webui/modules/processing.py", line 411, in create_infotext
    negative_prompt_text = "\nNegative prompt: " + p.negative_prompt if p.negative_prompt else ""
TypeError: can only concatenate str (not "tuple") to str
```

**Comment by 7eu7d7** [comment]
fix in new version
