### ISSUE TITLE
Cannot load embeddings on M1 Pro Macbook

### ISSUE THREAD

**Issue by lxy764139720** [7eu7d7/DreamArtist-sd-webui-extension#50]
I created an embedding named keqing, initialization text is girl, initialization text(negative) is *, on my M1 Pro macbook.
When restart the web-ui to loading the embeddings, the error was:
```
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7d13c797] from /Users/lxy/PycharmProjects/stable-diffusion-webui/models/Stable-diffusion/nsfw_pro.ckpt
Applying cross attention optimization (InvokeAI).
Model loaded.
Error verifying pickled file from /Users/lxy/PycharmProjects/stable-diffusion-webui/embeddings/keqing.pt:
Traceback (most recent call last):
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 89, in check_pt
    unpickler.load()
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 62, in find_class
    raise Exception(f"global '{module}/{name}' is forbidden")
Exception: global 'torch._utils/_rebuild_device_tensor_from_numpy' is forbidden


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Error loading emedding keqing.pt:
Traceback (most recent call last):
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 134, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 104, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Error verifying pickled file from /Users/lxy/PycharmProjects/stable-diffusion-webui/embeddings/keqing-neg.pt:
Traceback (most recent call last):
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 89, in check_pt
    unpickler.load()
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/safe.py", line 62, in find_class
    raise Exception(f"global '{module}/{name}' is forbidden")
Exception: global 'torch._utils/_rebuild_device_tensor_from_numpy' is forbidden


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.


Error loading emedding keqing-neg.pt:
Traceback (most recent call last):
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 134, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "/Users/lxy/PycharmProjects/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 104, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```
My pytorch version is as follows:
open-clip-torch         2.7.0
pytorch-lightning       1.7.6
torch                   1.12.1
torchdiffeq             0.2.3
torchmetrics            0.10.3
torchsde                0.2.5
torchvision             0.13.1

Here are some related issues I found:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5634
https://discuss.pytorch.org/t/cant-get-attribute-rebuild-parameter-on-module-torch-utils/32603
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5431

**Comment by lxy764139720** [comment]
Solved now! Just follow this issue and pull the latest repo of sd web-ui and restart. For me, I encountered the ModuleNotFoundError, and simply 'pip install blendmodes' worked for me.
