### ISSUE TITLE
请问dreamartist是需要16gb vram才能运作吗？

### ISSUE THREAD

**Issue by Mr0KL** [7eu7d7/DreamArtist-sd-webui-extension#52]
Error completing request
Arguments: ('zxcweasd', 114514, '0.003', 1, 'F:\\ai\\asdggg', 'dream_artist', 512, 512, 8000, 100, 500, 'F:\\ai\\stable-diffusion-webui\\textual_inversion_templates\\subject.txt', False, False, '', '', 20, 0, 7, -1.0, 512, 512, '3.0', '', True, True, False, 0.74, 1, 1.0, 25.0, 1.0, 25.0, 0.9, 0.999, False, 1, False, '0.000005') {}
Traceback (most recent call last):
  File "F:\ai\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "F:\ai\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "F:\ai\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 32, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "F:\ai\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 557, in train_embedding
    loss.backward()
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "F:\ai\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 8.00 GiB total capacity; 5.31 GiB already allocated; 0 bytes free; 6.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

每次尝试跑的时候都会弹出这个问题还是有什么方法可以解决吗？

**Comment by mart-hill** [comment]
Yup, it can even throw this error on 24GB card.

**Comment by IrisRainbowNeko** [comment]
减少图片大小或者batch size
