### ISSUE TITLE
ValueError: some parameters appear in more than one parameter group

### ISSUE THREAD

**Issue by Gushousekai195** [7eu7d7/DreamArtist-sd-webui-extension#54]
This happens after interrupting training, adding words to the prompt in the txt2img tab, and trying to resume training.

What does it mean?

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/ui.py", line 32, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/cptuning.py", line 491, in train_embedding
    optimizer_unet = torch.optim.AdamW([
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adamw.py", line 92, in __init__
    super(AdamW, self).__init__(params, defaults)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 66, in __init__
    self.add_param_group(param_group)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 346, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")
ValueError: some parameters appear in more than one parameter group`

**Comment by Gushousekai195** [comment]
It even happens when trying to resume training with the same exact prompt as before!

**Comment by Gushousekai195** [comment]
@7eu7d7
