### ISSUE TITLE
Train Embedding Button Inoperable Since Last Auto1111 Update

### ISSUE THREAD

**Issue by thenolifer** [7eu7d7/DreamArtist-sd-webui-extension#56]
Confirmed issue exists with two users, one using current DreamArtist commit, one using previous Commit. 

When using the latest commit of Auto1111, clicking the Train Embedding button does absolutely nothing. No change in the console, no message in the UI.

**Comment by mykeehu** [comment]
Ok, here is error from Chrome console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
    at requestProgress ((index):1532:50)
    at start_training_dreamartist ((index):1941:5)
    at eval (eval at <anonymous> (index.0b923826.js:75:2081), <anonymous>:3:48)
    at index.0b923826.js:34:32309
    at HTMLButtonElement.<anonymous> (index.0b923826.js:76:2455)
    at index.0b923826.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.ae (index.0b923826.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.0b923826.js:4:1266
```

**Comment by mykeehu** [comment]
We got a solution in @dwraco's [comment](https://github.com/7eu7d7/DreamArtist-sd-webui-extension/commit/a9db06d8437d9f2de707e13da68a3c7358bd2d32#commitcomment-96571181), I'm about to try it!

**Comment by IrisRainbowNeko** [comment]
Fix in new verison
