### ISSUE TITLE
Train Embedding button doesn't work

### ISSUE THREAD

**Issue by HotChocut** [7eu7d7/DreamArtist-sd-webui-extension#57]
Pressing the train embedding button doesn't do anything, console doesn't even respond so there are no error messages for me to go off of, I've tried uninstalling other extensions including dreambooth as well as a clean install of webUI but the problem still persists. 
Help would be much appreciated

(here's my webUI info)
```
DreamArtist-sd-webui-extension reversion: a9db06d8437d9f2de707e13da68a3c7358bd2d32

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 17c3864803ebb50615205271de687be96cfc96e8
SD-WebUI revision: e0e80050091ea7f58ae17c69f31d1b5de5e0ae20

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.14.dev0 installed.
[+] torch version 1.12.1+cu113 installed.
[+] torchvision version 0.13.1+cu113 installed.
```

**Comment by thenolifer** [comment]
I also raised this issue. I believe it is due to an Auto1111 interface update, not the DreamArtist extension itself, because I tried going back to the previous DreamArtist version and it is still broken.

**Comment by dwraco** [comment]
I noticed this as well. The relevant change appears to be in commit d8b90ac121cbf0c18b1dc9d56a5e1d14ca51e74e in the Automatic1111 repo.

commit d8b90ac121cbf0c18b1dc9d56a5e1d14ca51e74e
Author: AUTOMATIC <16777216c@gmail.com>
Date:   Sun Jan 15 18:50:56 2023 +0300

    big rework of progressbar/preview system to allow multiple users to prompts at the same time and do not get previews of each other


The requestProgress() function in javascript/progressbar.js changed and now expects additional arguments that DreamArtist does not pass.

New version
```
function requestProgress(id_task, progressbarContainer, gallery, atEnd, onProgress){
    var dateStart = new Date()
    var wasEverActive = false
    var parentProgressbar = progressbarContainer.parentNode
    var parentGallery = gallery.parentNode
```

Old version
```
function requestProgress(id_part){
    btn = gradioApp().getElementById(id_part+"_check_progress_initial");
    if(btn==null) return;
```

When I inspect my browser console after clicking the Train Embedding button in DreamArtist's tab:

Uncaught (in promise) TypeError: progressbarContainer is undefined
    requestProgress (index):1533
    start_training_dreamartist (index):1934
    anonymous index.0b923826.js line 75 > AsyncFunction:3
    ac index.0b923826.js:34
    Nt index.0b923826.js:76
    ae index.0b923826.js:4
    ae index.0b923826.js:4
    _ Button.svelte:10
    ae index.0b923826.js:4
    ae index.0b923826.js:4
    B Button.svelte:9
127.0.0.1:7860:1533:29


DreamArtist's javascript

```
<!-- dream_artist.js --><script>
function start_training_dreamartist(){
    requestProgress('da')
    gradioApp().querySelector('#da_error').innerHTML=''

    return args_to_array(arguments)
}
```

It only passes one argument to requestProgress, causing an undefined variable error right away in the new version of the function.

```
function requestProgress(id_task, progressbarContainer, gallery, atEnd, onProgress){
    var dateStart = new Date()
    var wasEverActive = false
    **var parentProgressbar = progressbarContainer.parentNode**
    var parentGallery = gallery.parentNode
```

**Comment by mcbradd** [comment]
You can update dream_artist.js to this to make the button work again, without progress updates in the UI. You can still see them in the terminal.
`function start_training_dreamartist() {
    gradioApp().querySelector('#sp_error').innerHTML = '';
    return args_to_array(arguments);
}

onUiUpdate(function () {
    check_gallery('sp_gallery')
})`

**Comment by dwraco** [comment]
Thanks, @mcbradd. That did the trick for me!

**Comment by mykeehu** [comment]
@mcbradd I[ modified two files](https://github.com/7eu7d7/DreamArtist-sd-webui-extension/issues/56#issuecomment-1385885338) based on TI at yesterday, but I get float error. Unfortunately @dwraco's solution didn't help either. It seems I need to rework the files more thoroughly, but unfortunately I'm not a programmer, I just followed the logic.

**Comment by HotChocut** [comment]
The branch by @jjtolton seems to have fixed it for me, I used [this](https://github.com/jjtolton/DreamArtist-sd-webui-extension/tree/6e7d12c392e1d276ccbc8dbe7c1e25c1179a94aa) commit. I'll leave the issue open for now but when the repository either gets merged or the issue get fixed on it's own I'll close it. Thanks @jjtolton for the solution!

**Comment by thenolifer** [comment]
I second this - the commit from @jjtolton has fixed the issue! Thank you!

**Comment by kenster4000** [comment]
I'm having the Train Embedding button not responding issue still - latest update for DA and A1111 :-/

**Comment by HotChocut** [comment]
@kenster4000 have you tried [this](https://github.com/jjtolton/DreamArtist-sd-webui-extension/tree/6e7d12c392e1d276ccbc8dbe7c1e25c1179a94aa) commit of DreamArtist?

**Comment by jjtolton** [comment]
> I'm having the Train Embedding button not responding issue still - latest update for DA and A1111 :-/ 

You can pull my fork if you don't want to wait for the dev to merge the PR.

**Comment by kenster4000** [comment]
Thanks @HotChocut and @jjtolton - I just pulled the fork... it starts but I get this error right at step 22:
"ValueError: cannot convert float NaN to integer"

Full Error:
"Preparing dataset...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.25it/s]
[Epoch 24: 0/1]loss: nan, grad:nan, grad_neg:nan, lr_unet:5.0000000000000004e-08:   0%| | 24/8000 [00:10<1:00:32,  2.20
Error completing request
Arguments: ('task(wc67pzmxeeqb5c7)', 'Style-Underground-Deb', 114514, '0.003', 1, 'C:\\Users\\Ken\\Downloads\\DA', 'dream_artist', 512, 512, 8000, 25, 25, 'E:\\__workspace\\stable-diffusion-webui\\textual_inversion_templates\\subject.txt', True, True, 'Style-Underground-Deb', 'Style-Underground-Deb-neg, 3d, cartoon, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name', 30, 0, 7, 3213212.0, 512, 512, '3.0', '', True, False, False, 1, 1, 1.0, 25.0, 1.0, 25.0, 0.9, 0.999, False, 1, False, '0.000005') {}
Traceback (most recent call last):
  File "E:\__workspace\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\__workspace\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\__workspace\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 32, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "E:\__workspace\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 644, in train_embedding
    processed = processing.process_images(p)
  File "E:\__workspace\stable-diffusion-webui\modules\processing.py", line 485, in process_images
    res = process_images_inner(p)
  File "E:\__workspace\stable-diffusion-webui\modules\processing.py", line 616, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "E:\__workspace\stable-diffusion-webui\modules\processing.py", line 571, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "E:\__workspace\stable-diffusion-webui\modules\prompt_parser.py", line 140, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "E:\__workspace\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "e:\__workspace\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\__workspace\stable-diffusion-webui\modules\sd_hijack_clip.py", line 233, in forward
    embeddings_list = ", ".join([f'{name} [{embedding.checksum()}]' for name, embedding in used_embeddings.items()])
  File "E:\__workspace\stable-diffusion-webui\modules\sd_hijack_clip.py", line 233, in <listcomp>
    embeddings_list = ", ".join([f'{name} [{embedding.checksum()}]' for name, embedding in used_embeddings.items()])
  File "E:\__workspace\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 84, in checksum
    self.cached_checksum = f'{const_hash(self.vec.reshape(-1) * 100) & 0xffff:04x}'
  File "E:\__workspace\stable-diffusion-webui\modules\textual_inversion\textual_inversion.py", line 81, in const_hash
    r = (r * 281 ^ int(v) * 997) & 0xFFFFFFFF
ValueError: cannot convert float NaN to integer"

**Comment by kenster4000** [comment]
Changed when it saves out an embedding file from 25 to step 100... as soon as it gets to 100 it produces the same error. Definitely where it is having issues.

**Comment by kenster4000** [comment]
I have noticed the loss is at NaN during training. Could this be part of the issue?

**Comment by jjtolton** [comment]
What version of AD1111 are you using so I can check?

**Comment by kenster4000** [comment]
Away from computer - but is the latest pull

**Comment by jjtolton** [comment]
@kenster4000 I ran SD commit `1d8e06d542176beade37d2d36cb57460c3c6772f` with DA commit (my fork/master) `fa6c411432a460d00eead914974e470376c74c5c` and was unable to get that bug.  Could you verify you've got the correct commits?

**Comment by HotChocut** [comment]
I was having the (hopefully same) issue of crashing when trying to save during training a while back, while I never really got a definite fix what I did to train was set the saving frequency to 0 so it doesn't save while training, then saved when it was done. I eventually got it working correctly by just completely removing DreamArtist from my extensions folder and reinstalling random versions but with the new webui the only versions that work for me are the two by @jjtolton. (the [later](https://github.com/jjtolton/DreamArtist-sd-webui-extension/tree/6e7d12c392e1d276ccbc8dbe7c1e25c1179a94aa) one being the one I use now)

**Comment by Gushousekai195** [comment]
Also not working for me despite updating. DreamArtist is useless now.

**Comment by HotChocut** [comment]
@Gushousekai195 Updating as in trying the latest version or [this](https://github.com/jjtolton/DreamArtist-sd-webui-extension/tree/6e7d12c392e1d276ccbc8dbe7c1e25c1179a94aa) commit? If you haven't tried the commit I would give it a go, it fixed the issue for me.

**Comment by jjtolton** [comment]
> Also not working for me despite updating. DreamArtist is useless now.

As @HotChocut said, please delete your existing DA extension and install my fork until the dev merges in the changes.

**Comment by Gushousekai195** [comment]
> @Gushousekai195 Updating as in trying the latest version or [this](https://github.com/jjtolton/DreamArtist-sd-webui-extension/tree/6e7d12c392e1d276ccbc8dbe7c1e25c1179a94aa) commit? If you haven't tried the commit I would give it a go, it fixed the issue for me.

How do I install it with AUTO1111?

**Comment by Gushousekai195** [comment]
This happens during startup. What is it?

```
2023-02-11 21:51:10.496032: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-11 21:51:11.735016: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-11 21:51:11.735186: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-11 21:51:11.735212: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

**Comment by HotChocut** [comment]
There are several ways but I did it by going into my webui folder and deleting the "DreamArtist-sd-webui-extension" folder, then starting webui and using "install from url" with the link from the commit.

**Comment by Gushousekai195** [comment]
> There are several ways but I did it by going into my webui folder and deleting the "DreamArtist-sd-webui-extension" folder, then starting webui and using "install from url" with the link from the commit.

I did just that, but now this happens during the "Start Stable-Diffusion" part of the Colab:
This happens during startup. What is it?

```
2023-02-11 21:51:10.496032: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-11 21:51:11.735016: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-11 21:51:11.735186: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-11 21:51:11.735212: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

**Comment by HotChocut** [comment]
Which AUTO1111 are you using? I use [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui) one. (one the latest version)

**Comment by Gushousekai195** [comment]
> Which AUTO1111 are you using? I use [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui) one. (on the latest version)

https://github.com/TheLastBen/fast-stable-diffusion because it's supposedly faster.

**Comment by HotChocut** [comment]
I'm not very familiar with this one sorry, from what I can see it uses colab instead of your own GPU? I can't really test it right now as I have my computer training but when it's done I'll check it out.

**Comment by Gushousekai195** [comment]
> I'm not very familiar with this one sorry, from what I can see it uses colab instead of your own GPU? I can't really test it right now as I have my computer training but when it's done I'll check it out.

Can't afford a GPU that can do it locally.

**Comment by Gushousekai195** [comment]
Can anybody else help me rn?

**Comment by Gushousekai195** [comment]
> I'm not very familiar with this one sorry, from what I can see it uses colab instead of your own GPU? I can't really test it right now as I have my computer training but when it's done I'll check it out.

Which Colab will work?
![image](https://user-images.githubusercontent.com/64454655/218283476-2305e5b8-ea3e-4feb-a480-b3c3d77a8198.png)

**Comment by HotChocut** [comment]
I found [this](https://github.com/TheLastBen/fast-stable-diffusion/issues/1398) post in the fast-stable-diffusion issues, it's about dreambooth rather than dreamartist but maybe it can help.

**Comment by Gushousekai195** [comment]
> I found [this](https://github.com/TheLastBen/fast-stable-diffusion/issues/1398) post in the fast-stable-diffusion issues, it's about dreambooth rather than dreamartist but maybe it can help.

I tried disconnecting and reconnecting (which I think means "Disconnect and Delete Runtime" and restart) and the warning still happens.

**Comment by Gushousekai195** [comment]
> I found [this](https://github.com/TheLastBen/fast-stable-diffusion/issues/1398) post in the fast-stable-diffusion issues, it's about dreambooth rather than dreamartist but maybe it can help.

Also, when I train with DreamArtist and it saves an image to the log directory, this happens and training stops:
`Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
res = list(func(*args, **kwargs))
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
res = func(*args, **kwargs)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/ui.py", line 32, in train_embedding
embedding, filename = dream_artist.cptuning.train_embedding(*args)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/DreamArtist-sd-webui-extension/scripts/dream_artist/cptuning.py", line 559, in train_embedding
loss.backward()
File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 488, in backward
torch.autograd.backward(
File "/usr/local/lib/python3.8/dist-packages/torch/autograd/init.py", line 197, in backward
Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 267, in apply
return user_fn(self, *args)
File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/modules/diffusionmodules/util.py", line 142, in backward
input_grads = torch.autograd.grad(
File "/usr/local/lib/python3.8/dist-packages/torch/autograd/init.py", line 300, in grad
return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors does not require grad`

**Comment by HotChocut** [comment]
Try setting the preview image steps to 0 so that it doesn't save any previews

**Comment by Gushousekai195** [comment]
> Try setting the preview image steps to 0 so that it doesn't save any previews

Then how will I know how the training is going?

**Comment by HotChocut** [comment]
You won't

**Comment by PiPerson7472** [comment]
I am also getting some issues. Getting this when I try and start training

Error completing request
Arguments: ('task(jmfrz6z2en6l3sp)', 'spaghettimaker-da-sd1.5', 114514, '0.003', 1, 'E:\\Media\\Text-Image\\trainingsmall', 'dream_artist', 512, 512, 8000, 100, 500, 'E:\\Media\\Text-Image\\stable-diffusion-webui\\textual_inversion_templates\\style.txt', True, True, '', '', 20, 0, 7, -1.0, 512, 512, '3.0', '', True, True, True, 1, 1, 0.97, 25.0, 1.0, 25.0, 0.9, 0.999, False, 1, False, '0.000005') {}
Traceback (most recent call last):
  File "E:\Media\Text-Image\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\Media\Text-Image\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\Media\Text-Image\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 32, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
TypeError: train_embedding() takes 39 positional arguments but 40 were given

**Comment by pupdike** [comment]
By switching to jjtolton's branch I was able to get it working on the latest automatic1111, but only after disabling the progress images (setting it to 0.)

**Comment by Gushousekai195** [comment]
Any idea when @7eu7d7 is coming back to fix this extension?

**Comment by HotChocut** [comment]
Honestly, I wouldn't count on it.

**Comment by ina6ra** [comment]
I was stumped too and found a solution.
Using a supported repository instead of this worked for me.

https://github.com/7eu7d7/DreamArtist-sd-webui-extension/pull/58
https://github.com/jjtolton/DreamArtist-sd-webui-extension

**Comment by FurkanGozukara** [comment]
when i hit train nothing happens and nothing displayed in the cmd window

@7eu7d7 @Omegastick 

@jjtolton yours work?

**Comment by jjtolton** [comment]
@FurkanGozukara  https://github.com/7eu7d7/DreamArtist-sd-webui-extension/issues/65#issuecomment-1496261820

**Comment by 7eu7d7** [comment]
This bug is fixed in the new version
