### ISSUE TITLE
Training with Reconstruction throws Attribute Error

### ISSUE THREAD

**Issue by RainehDaze** [7eu7d7/DreamArtist-sd-webui-extension#63]
```
Traceback (most recent call last):
  File "C:\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\automatic1111\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 32, in train_embedding
    embedding, filename = dream_artist.cptuning.train_embedding(*args)
  File "C:\automatic1111\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 540, in train_embedding
    x_samples_ddim = shared.sd_model.decode_first_stage.__wrapped__(shared.sd_model, output[2])  # forward with grad
AttributeError: 'function' object has no attribute '__wrapped__'
```

I think this may be due to upstream changes; it was fine earlier.

**Comment by baymin0220** [comment]
@RainehDaze Do you solve this errors?which version is fine?

**Comment by RainehDaze** [comment]
@baymin0220 I've just been running without reconstruction.

**Comment by Nephyrin** [comment]
```diff
diff --git a/scripts/dream_artist/cptuning.py b/scripts/dream_artist/cptuning.py
index b7c1705..7894b6e 100644
--- a/scripts/dream_artist/cptuning.py
+++ b/scripts/dream_artist/cptuning.py
@@ -537,7 +537,7 @@ def train_embedding(_, embedding_name, seed, learn_rate, batch_size, data_root,
                 output = shared.sd_model(x, c_in, scale=(cfg_l, cfg_h), att_mask=None, dy_cfg_f=dy_cfg_f)
 
             if disc is not None or use_rec:
-                x_samples_ddim = shared.sd_model.decode_first_stage.__wrapped__(shared.sd_model, output[2])  # forward with grad
+                x_samples_ddim = shared.sd_model.decode_first_stage(output[2])  # forward with grad
 
             if disc is not None:
                 # loss = ce(disc.get_all(x_samples_ddim), disc_label)
```

This fixes it, though I don't fully appreciate the implications of `decode_first_stage` no longer being a wrapped function or why that was being bypassed before.

**Comment by IrisRainbowNeko** [comment]
Fix in new version
