### ISSUE TITLE
Error loading script: dream_artist_main.py

### ISSUE THREAD

**Issue by jtaxiexpress** [7eu7d7/DreamArtist-sd-webui-extension#73]
# Issue
There are no Dream Artist Tab
![スクリーンショット 2023-10-17 160234](https://github.com/7eu7d7/DreamArtist-sd-webui-extension/assets/86914073/e23766ab-a8a4-4f12-bfcb-7a5c046c783b)
## Enviroment
- version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  
- python: 3.10.6  
- torch: 2.0.1+cu118  
- xformers: 0.0.20  
- gradio: 3.41.2  •  checkpoint: [18ed2b6c48](https://google.com/search?q=18ed2b6c48fda400330e5dec9e6f4d714ef664869ea8d4021f12ba699b31da06)
### Error
```
*** Error loading script: dream_artist_main.py
    Traceback (most recent call last):
      File "C:\DiffusionProjects\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\DiffusionProjects\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\DiffusionProjects\stable-diffusion-webui\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist_main.py", line 10, in <module>
        from webui import wrap_gradio_gpu_call
    ImportError: cannot import name 'wrap_gradio_gpu_call' from 'webui' (C:\DiffusionProjects\stable-diffusion-webui\webui.py)
```f

**Comment by Samyi123** [comment]
https://github.com/7eu7d7/DreamArtist-sd-webui-extension/pull/74
